version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: aria_postgres
    environment:
      POSTGRES_DB: aria_db
      POSTGRES_USER: aria_user
      POSTGRES_PASSWORD: aria_password
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aria_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: aria_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aria.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - aria_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  aria_network:
    driver: bridge